"""make roles global and remove account_id

Revision ID: af4a67139858
Revises: fix_roles_unique
Create Date: 2025-12-14 11:00:38.079527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4a67139858'
down_revision: Union[str, Sequence[str], None] = 'fix_roles_unique'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_role_per_account'), 'roles', type_='unique')
    op.create_unique_constraint(None, 'roles', ['name'])
    op.drop_constraint(op.f('roles_account_id_fkey'), 'roles', type_='foreignkey')
    op.drop_column('roles', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('roles_account_id_fkey'), 'roles', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'roles', type_='unique')
    op.create_unique_constraint(op.f('unique_role_per_account'), 'roles', ['name', 'account_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
